from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

from PIL import Image, ImageDraw, ImageFont, ImageOps

from youtube_live import MachineStatus


COLS = 4
ROWS = 2
TILE_W = 480
TILE_H = 270
GRID_W = TILE_W * COLS
GRID_H = TILE_H * ROWS
BANNER_H = 80
IMG_W = GRID_W
IMG_H = GRID_H + BANNER_H

LABEL_PADDING_X = 14
LABEL_PADDING_Y = 10
LABEL_FONT_SIZE = 24
LABEL_BOX_PADDING_X = 12
LABEL_BOX_PADDING_Y = 6

OFFLINE_FONT_SIZE = 34
OFFLINE_LINE_SPACING = 10
BANNER_PADDING_X = 24
BANNER_FONT_SIZE = 28

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
LIVE_LABEL_BG = (0, 0, 0, 170)


def _load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    font_candidates = (
        Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"),
        Path("/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc"),
        Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"),
        Path("/usr/share/fonts/truetype/noto/NotoSansCJK-Bold.ttc"),
        Path("/usr/share/fonts/truetype/nanum/NanumGothic.ttf"),
        Path("/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf"),
        Path("C:/Windows/Fonts/malgun.ttf"),
        Path("C:/Windows/Fonts/malgunbd.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
    )

    for path in font_candidates:
        if path.exists():
            return ImageFont.truetype(str(path), size)

    return ImageFont.load_default()


def _text_size(
    draw: ImageDraw.ImageDraw,
    text: str,
    font: ImageFont.FreeTypeFont | ImageFont.ImageFont,
) -> tuple[int, int]:
    left, top, right, bottom = draw.textbbox((0, 0), text, font=font)
    return right - left, bottom - top


def _download_thumbnail(url: str) -> Image.Image | None:
    try:
        with urlopen(url, timeout=10) as response:
            return Image.open(BytesIO(response.read()))
    except (OSError, URLError):
        return None


def _fit_thumbnail(image: Image.Image) -> Image.Image:
    return ImageOps.fit(
        image.convert("RGB"),
        (TILE_W, TILE_H),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5),
    )


def _format_minutes_since(value: datetime | None, now: datetime) -> str | None:
    if value is None:
        return None

    minutes = max(0, int((now - value.astimezone(timezone.utc)).total_seconds() // 60))
    if minutes < 60:
        return f"{minutes}분 전 종료"

    hours = minutes // 60
    rest_minutes = minutes % 60
    if hours < 24 and rest_minutes:
        return f"{hours}시간 {rest_minutes}분 전 종료"
    if hours < 24:
        return f"{hours}시간 전 종료"

    days = hours // 24
    return f"{days}일 전 종료"


def _draw_live_label(image: Image.Image, x0: int, y0: int, label: str) -> None:
    overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    font = _load_font(LABEL_FONT_SIZE)
    text_w, text_h = _text_size(draw, label, font)

    box_x1 = x0 + TILE_W - LABEL_PADDING_X
    box_y1 = y0 + TILE_H - LABEL_PADDING_Y
    box_x0 = box_x1 - text_w - LABEL_BOX_PADDING_X * 2
    box_y0 = box_y1 - text_h - LABEL_BOX_PADDING_Y * 2
    text_x = box_x0 + LABEL_BOX_PADDING_X
    text_y = box_y0 + LABEL_BOX_PADDING_Y

    draw.rectangle((box_x0, box_y0, box_x1, box_y1), fill=LIVE_LABEL_BG)
    draw.text((text_x, text_y), label, fill=COLOR_WHITE, font=font)
    image.alpha_composite(overlay)


def _draw_centered_lines(
    draw: ImageDraw.ImageDraw,
    x0: int,
    y0: int,
    lines: list[str],
    font: ImageFont.FreeTypeFont | ImageFont.ImageFont,
) -> None:
    line_sizes = [_text_size(draw, line, font) for line in lines]
    total_h = sum(height for _width, height in line_sizes)
    total_h += OFFLINE_LINE_SPACING * (len(lines) - 1)
    y = y0 + (TILE_H - total_h) // 2

    for line, (text_w, text_h) in zip(lines, line_sizes):
        x = x0 + (TILE_W - text_w) // 2
        draw.text((x, y), line, fill=COLOR_WHITE, font=font)
        y += text_h + OFFLINE_LINE_SPACING


def _draw_offline_tile(
    draw: ImageDraw.ImageDraw,
    x0: int,
    y0: int,
    status: MachineStatus,
    now: datetime,
) -> None:
    draw.rectangle((x0, y0, x0 + TILE_W, y0 + TILE_H), fill=COLOR_BLACK)
    font = _load_font(OFFLINE_FONT_SIZE)
    lines = [status.label, "오프라인"]
    minutes_since = _format_minutes_since(status.last_ended_at, now)

    if minutes_since:
        lines.append(minutes_since)

    _draw_centered_lines(draw, x0, y0, lines, font)


def _draw_banner(image: Image.Image, timestamp: str) -> None:
    draw = ImageDraw.Draw(image)
    font = _load_font(BANNER_FONT_SIZE)
    left_text = f"{timestamp} @광주 게임플라자"
    right_text = "generated by @밀크봇"
    _left_w, left_h = _text_size(draw, left_text, font)
    right_w, right_h = _text_size(draw, right_text, font)
    left_y = GRID_H + (BANNER_H - left_h) // 2
    right_y = GRID_H + (BANNER_H - right_h) // 2

    draw.rectangle((0, GRID_H, IMG_W, IMG_H), fill=COLOR_BLACK)
    draw.text((BANNER_PADDING_X, left_y), left_text, fill=COLOR_WHITE, font=font)
    draw.text(
        (IMG_W - BANNER_PADDING_X - right_w, right_y),
        right_text,
        fill=COLOR_WHITE,
        font=font,
    )


def build_gameplaza_thumbnail_board(
    statuses: list[MachineStatus],
    timestamp: str,
    now: datetime | None = None,
) -> BytesIO:
    now = now or datetime.now(timezone.utc)
    image = Image.new("RGBA", (IMG_W, IMG_H), COLOR_BLACK + (255,))
    draw = ImageDraw.Draw(image)

    for index, status in enumerate(statuses[: COLS * ROWS]):
        row = index // COLS
        col = index % COLS
        x0 = col * TILE_W
        y0 = row * TILE_H

        thumbnail = None
        if status.is_live and status.thumbnail_url:
            thumbnail = _download_thumbnail(status.thumbnail_url)

        if thumbnail:
            image.paste(_fit_thumbnail(thumbnail).convert("RGBA"), (x0, y0))
            _draw_live_label(image, x0, y0, status.label)
        else:
            _draw_offline_tile(draw, x0, y0, status, now)

    _draw_banner(image, timestamp)

    buffer = BytesIO()
    image.convert("RGB").save(buffer, format="PNG", optimize=True)
    buffer.seek(0)
    return buffer
